### ISSUE TITLE
Error loading `tslib` helper library in node 18

### ISSUE THREAD

**Issue by GaborTorma** [neo-hack/dayjs-plugin-template#2]
**Screenshots**
![Snag_33d510d](https://github.com/neo-hack/dayjs-plugin-template/assets/11255009/cbbe4519-39a7-4463-bb44-6d282c5c2774)

**To Reproduce**
1. git clone
2. pnpm i
3. pnpm dev or pnpm build

**Comment by JiangWeixian** [comment]
https://github.com/ezolenko/rollup-plugin-typescript2/issues/286 upload `rollup-plugin-typescript2` to `0.31.0`
